sites:
  redragon:
    url: https://listado.mercadolibre.com.ar/mouse-redragon#D[A:mouse%20redragon]
    queries:
      homepage_article_links: '.ui-search-item__group__element'
      article_score: '.ui-pdp-reviews__rating__summary__average'
      article_title: '.ui-pdp-title'
  razer:
    url: https://listado.mercadolibre.com.ar/mouse-razer#D[A:mouse%20razer]
    queries:
      homepage_article_links: '.ui-search-item__group__element'
      article_score: '.ui-pdp-reviews__rating__summary__average'
      article_title: '.ui-pdp-title'
  logitech:
    url: https://listado.mercadolibre.com.ar/mouse-logitech#D[A:mouse%20logitech]
    queries:
      homepage_article_links: '.ui-search-item__group__element'
      article_score: '.ui-pdp-reviews__rating__summary__average'
      article_title: '.ui-pdp-title'
